import { startMessage, donateMessage } from './constants.js';
import { getRandomPositiveReaction, escapeHtml, splitEmojis } from './helper.js';
import { editStatus, progressText, errorText } from './broadcast.js';
import { logger } from './logger.js';
import { uiText, uiButton } from './font.js';

const TARGETS={users:['users'],groups:['groups'],channels:['channels'],all:['users','groups','channels']};
const DEFAULT_WELCOME='👋 Welcome {mention} to <b>{group}</b>!\n\nPlease read the group rules and enjoy your stay. ❤️';
const DEFAULT_JOIN='👋 Hello {mention}!\n\nYour request to join <b>{group}</b> has been received.\nPlease wait while an admin reviews it. ✨';
const MUTE_PERMISSIONS={can_send_messages:false,can_send_audios:false,can_send_documents:false,can_send_photos:false,can_send_videos:false,can_send_video_notes:false,can_send_voice_notes:false,can_send_polls:false,can_send_other_messages:false,can_add_web_page_previews:false,can_change_info:false,can_invite_users:false,can_pin_messages:false,can_manage_topics:false};
const UNMUTE_PERMISSIONS={can_send_messages:true,can_send_audios:true,can_send_documents:true,can_send_photos:true,can_send_videos:true,can_send_video_notes:true,can_send_voice_notes:true,can_send_polls:true,can_send_other_messages:true,can_add_web_page_previews:true,can_change_info:false,can_invite_users:false,can_pin_messages:false,can_manage_topics:true};
const COLORS=['primary','success','danger'];
async function safe(task){try{return await task()}catch(e){logger.warn('Storage error:',e.message)}}

export async function onUpdate(data,api,Reactions,RestrictedChats,botUsername,RandomLevel,options={}){
 const {store=null,adminIds=[]}=options;
 if(data.chat_join_request){await handleJoinRequest(data.chat_join_request,api,store,options);return}
 if(data.chat_member){await handleChatMember(data.chat_member,api,store);return}
 if(data.callback_query){await onCallback(data.callback_query,api,options);return}
 if(data.my_chat_member){const {chat,new_chat_member}=data.my_chat_member;if(store){if(['kicked','left'].includes(new_chat_member?.status))await safe(()=>store.remove(chat.id));else await safe(()=>store.add(chat.id,chat.type,{force:true}));}return}
 if(data.message||data.channel_post){
  const content=data.message||data.channel_post,chatId=content.chat.id,messageId=content.message_id,text=content.text||content.caption||'';
  if(store)await safe(()=>store.add(chatId,content.chat.type));
  const parts=text.trim().split(/\s+/),raw=parts[0]||'',arg=parts.slice(1).join(' '),command=raw.split('@')[0].toLowerCase();
  const isPrivate=content.chat.type==='private',isGroup=['group','supergroup'].includes(content.chat.type),isChannel=content.chat.type==='channel';
  const isGlobalAdmin=!!data.message&&isPrivate&&adminIds.includes(content.from?.id);
  const forwardedChannel=isPrivate?getForwardedChannel(content.reply_to_message||content):null;
  if(store&&content.from?.id&&isPrivate&&!command.startsWith('/')){const pending=await store.getPending(content.from.id);if(pending){await finishPending(api,content,pending,Reactions,store,botUsername,options);return}}
  if(data.message&&command==='/start')return sendStart(api,content,botUsername,options,arg);
  if(data.message&&command==='/help')return showHelp(api,content,botUsername,options);
  if(data.message&&(command==='/groupsetting'||(command==='/welcome'&&isGroup)))return handleGroupSettingCommand(api,content,store,options,forwardedChannel);
  if(data.message&&command==='/connectchannel'&&isPrivate)return connectChannelCommand(api,content,store,options,forwardedChannel,arg);
  if(data.message&&command==='/mychannels'&&isPrivate)return showConnections(api,chatId,content.from.id,store,options,'channel');
  if(data.message&&command==='/joinsetting'&&isPrivate)return openChannelFromForward(api,content,store,options,forwardedChannel);
  if(data.message&&command==='/reactions')return showReactionSettings(api,content,Reactions,store,options,forwardedChannel);
  if(data.message&&command==='/donate')return sendDonate(api,chatId,options);
  if(data.message&&isGroup&&(command==='/reactions_on'||command==='/reactions_off'))return setGroupReactionState(api,content,command==='/reactions_on',store);
  if(data.message&&isPrivate&&forwardedChannel&&(command==='/reactions_on'||command==='/reactions_off'))return setForwardedChannelState(api,content,forwardedChannel,command==='/reactions_on',store);
  if(isGlobalAdmin&&(command==='/stats'||command==='/users'))return sendStats(api,chatId,store);
  if(isGlobalAdmin&&command==='/broadcast')return askBroadcast(api,content,options);
  if(isGroup&&content.from?.id&&content.new_chat_members===undefined){
   if(store && !content.from.is_bot && !command.startsWith('/')){
    const blocked=await enforceRequiredChannels(api,content,store);
    if(blocked)return;
   }
   const custom=store?await store.getReactions(chatId):null,active=custom?.length?custom:Reactions,enabled=store?await store.isReactionsEnabled(chatId):true;
   if(enabled&&active.length&&!RestrictedChats.includes(chatId)&&messageId&&Math.random()<=1-(RandomLevel/10))await api.setMessageReaction(chatId,messageId,getRandomPositiveReaction(active));
  }else if(isChannel){
   const custom=store?await store.getReactions(chatId):null,active=custom?.length?custom:Reactions,enabled=store?await store.isReactionsEnabled(chatId):true;
   if(enabled&&active.length&&!RestrictedChats.includes(chatId)&&messageId)await api.setMessageReaction(chatId,messageId,getRandomPositiveReaction(active));
  }
 }
 if(data.pre_checkout_query)await api.answerPreCheckoutQuery(data.pre_checkout_query.id,true);
}

async function enforceRequiredChannels(api,content,store){
 const groupId=content.chat.id,userId=content.from.id;
 const s=await store.getGroupSettings(groupId),channels=getRequiredChannels(s);
 if(!s.required_enabled || !channels.length)return false;
 const missing=[];
 for(const ch of channels){
  try{
   const m=await api.getChatMember(ch.id,userId);
   const joined=['member','administrator','creator'].includes(m?.status)||(m?.status==='restricted'&&m?.is_member===true);
   if(!joined)missing.push(ch);
  }catch(e){missing.push(ch);logger.warn(`Required channel check failed: ${e.message}`)}
 }
 if(!missing.length)return false;
 try{await api.restrictChatMember(groupId,userId,MUTE_PERMISSIONS)}catch(e){logger.warn(`Mute failed: ${e.message}`)}
 try{await api.deleteMessage(groupId,content.message_id)}catch(_){}
 const rows=missing.map(ch=>[Object.assign(uiButton(`📢 ${shortChannelName(ch)}`,'primary'),{url:ch.url||`https://t.me/${String(ch.id).replace(/^-100/,'')}`})]);
 rows.push(...(normalizeButtons(s.required_buttons)||[]));
 rows.push([Object.assign(uiButton('✅ CHECK & UNMUTE','success'),{callback_data:`reqcheck:${groupId}`})]);
 try{await api.sendMessage(groupId,`${mention(content.from)} ${uiText('🔐 Please join all required channels before chatting in this group.\n\nJoin every channel above, then tap Check & Unmute.')}`,rows)}catch(e){logger.warn(`Required-channel notice failed: ${e.message}`)}
 return true;
}

async function handleChatMember(update,api,store){
 const chat=update.chat,member=update.new_chat_member,old=update.old_chat_member?.status,newStatus=member?.status;
 if(!store||!chat||!['group','supergroup'].includes(chat.type))return;
 await safe(()=>store.add(chat.id,chat.type));
 if(!['member','administrator'].includes(newStatus)||['member','administrator'].includes(old)||!member?.user||member.user.is_bot)return;
 const s=await store.getGroupSettings(chat.id);const channels=getRequiredChannels(s);if(s.required_enabled && channels.length){
  const missing=[];for(const ch of channels){let joined=false;try{const m=await api.getChatMember(ch.id,member.user.id);joined=['member','administrator','creator'].includes(m?.status)||(m?.status==='restricted'&&m?.is_member)}catch(e){logger.warn(`Required channel check failed: ${e.message}`)}if(!joined)missing.push(ch)}
  if(missing.length){try{await api.restrictChatMember(chat.id,member.user.id,MUTE_PERMISSIONS)}catch(e){logger.warn(`Mute failed: ${e.message}`)}const rows=missing.map(ch=>[Object.assign(uiButton(`📢 ${shortChannelName(ch)}`,'primary'),{url:ch.url||`https://t.me/${String(ch.id).replace(/^-100/,'')}`})]);rows.push(...normalizeButtons(s.required_buttons)||[]);rows.push([Object.assign(uiButton('✅ CHECK & UNMUTE','success'),{callback_data:`reqcheck:${chat.id}`})]);try{await api.sendMessage(chat.id,`${mention(member.user)} ${uiText('🔐 Please join all required channels before chatting in this group.\n\nJoin every channel above, then tap Check & Unmute.')}`,rows)}catch(_){}return}
 }
 if(!s.welcome_enabled)return;const wt=renderTemplate(s.welcome_message||DEFAULT_WELCOME,member.user,chat),kb=normalizeButtons(s.welcome_buttons);try{if(s.welcome_mode==='only_user')await api.sendEphemeralMessage(chat.id,member.user.id,wt,kb);else await api.sendMessage(chat.id,wt,kb)}catch(e){if(s.welcome_mode==='only_user')try{await api.sendMessage(member.user.id,wt,kb)}catch(_) {}}
}

async function handleJoinRequest(request,api,store){if(!store)return;const chat=request.chat,user=request.from;if(!chat?.id||!user?.id)return;await safe(()=>store.add(user.id,'private'));await safe(()=>store.addChannelRequestUser?.(user.id));await safe(()=>store.add(chat.id,chat.type));const s=await store.getGroupSettings(chat.id);if(!s.join_enabled)return;const recipient=request.user_chat_id||user.id,text=renderTemplate(s.join_message||DEFAULT_JOIN,user,chat),keyboard=normalizeButtons(s.join_buttons);try{await api.sendMessage(recipient,text,keyboard)}catch(e){logger.warn(`Join request notification failed: ${e.message}`)}if(s.join_mode==='auto_accept')try{await api.approveChatJoinRequest(chat.id,user.id);try{await api.sendMessage(recipient,renderTemplate('<b>✅ Your request has been accepted.</b>\nWelcome to {group}! 🎉',user,chat),keyboard)}catch(_){}}catch(e){logger.warn(`Auto-accept failed: ${e.message}`)}}
function renderTemplate(text,user,chat){const name=escapeHtml([user?.first_name,user?.last_name].filter(Boolean).join(' ')||'there'),username=user?.username?`@${escapeHtml(user.username)}`:name,mention=`<a href="tg://user?id=${user?.id}">${name}</a>`,group=escapeHtml(chat?.title||'this chat');return String(text).replaceAll('{name}',name).replaceAll('{username}',username).replaceAll('{mention}',mention).replaceAll('{group}',group)}
function mention(user){return `<a href="tg://user?id=${user.id}">${escapeHtml(user.first_name||'User')}</a>`}
function normalizeButtons(buttons){if(!Array.isArray(buttons))return null;const rows=[];for(const item of buttons){if(Array.isArray(item)){const r=item.filter(x=>x?.text&&x?.url).slice(0,2).map(x=>({text:x.text,url:x.url,...(COLORS.includes(x.style)?{style:x.style}:{})}));if(r.length)rows.push(r)}else if(item?.text&&item?.url)rows.push([{text:item.text,url:item.url,...(COLORS.includes(item.style)?{style:item.style}:{})}]);}return rows.length?rows:null}
function getForwardedChannel(message){const o=message?.forward_origin;return o?.type==='channel'&&o.chat?.id?o.chat:null}
async function verifyAdmin(api,chatId,userId){try{return ['creator','administrator'].includes((await api.getChatMember(chatId,userId))?.status)}catch{return false}}
async function verifyGroupAdmin(api,content){
 try {
  if(!content?.chat?.id||!content?.from?.id)return false;
  if(!['group','supergroup'].includes(content.chat.type))return false;
  return ['creator','administrator'].includes((await api.getChatMember(content.chat.id,content.from.id))?.status);
 } catch { return false; }
}
async function verifyBotAdmin(api,chatId){try{const me=await api.getMe();const m=await api.getChatMember(chatId,me.id);return ['creator','administrator'].includes(m?.status)}catch{return false}}
async function connectAndOpenChannel(api,content,store,options,channel){
 if(!channel?.id)return api.sendMessage(content.chat.id,uiText('⚠️ I could not identify that channel. Please forward a post from the channel again.'));
 const check=await verifyChannelSetup(api,channel.id);
 if(!check.ok)return api.sendMessage(content.chat.id,uiText(`⚠️ ${check.error}`));
 if(!(await verifyAdmin(api,channel.id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ You must be a channel admin to connect this channel.'));
 await store.connect(content.from.id,channel.id,'channel',check.chat.title||channel.title||'Channel');
 return showChannelSettings(api,content.chat.id,content.from.id,channel.id,store,options);
}
async function verifyChannelSetup(api,chatId){try{const c=await api.getChat(chatId);if(c?.type!=='channel')return {ok:false,error:'That chat is not a channel.'};if(!(await verifyBotAdmin(api,chatId)))return {ok:false,error:'Make me an admin in that channel first.'};return {ok:true,chat:c}}catch{return {ok:false,error:'I could not find/verify that channel. For a private channel, forward one of its posts to me after making me an admin.'}}}
async function notConfigured(api,id){return api.sendMessage(id,uiText('⚠️ Database is not configured.'))}

async function handleGroupSettingCommand(api,content,store,options,forwardedChannel){if(!store)return notConfigured(api,content.chat.id);if(['group','supergroup'].includes(content.chat.type)){if(!(await verifyGroupAdmin(api,content)))return api.sendEphemeralMessage(content.chat.id,content.from?.id,uiText('⚠️ Only group admins can use /groupsetting.'));await store.connect(content.from.id,content.chat.id,'group',content.chat.title||'Group');const url=`https://t.me/${options.botUsername}?start=group_${content.chat.id}`;const text=uiText('⚙️ This group is connected. Open the private settings panel to manage everything easily.');try{return await api.sendEphemeralMessage(content.chat.id,content.from.id,text,[[Object.assign(uiButton('⚙️ OPEN GROUP SETTINGS','primary'),{url})]])}catch{return api.sendMessage(content.chat.id,text,[[Object.assign(uiButton('⚙️ OPEN GROUP SETTINGS','primary'),{url})]])}}if(content.chat.type==='private'){if(forwardedChannel)return connectAndOpenChannel(api,content,store,options,forwardedChannel);return showConnections(api,content.chat.id,content.from.id,store,options)}return api.sendMessage(content.chat.id,uiText('⚠️ Use /groupsetting in a group or in my private chat.'))}

async function showConnections(api,chatId,userId,store,options,onlyKind=null){const list=await store.connections(userId),groups=list.filter(x=>x.kind==='group'),channels=list.filter(x=>x.kind==='channel');const selected=onlyKind==='channel'?channels:onlyKind==='group'?groups:list;const rows=[];if(!onlyKind){rows.push([Object.assign(uiButton('👥 GROUPS','primary'),{callback_data:'pick:group'}),Object.assign(uiButton('📢 CHANNELS','primary'),{callback_data:'pick:channel'})]);rows.push([Object.assign(uiButton('➕ CONNECT GROUP','success'),{callback_data:'connect:group'}),Object.assign(uiButton('➕ CONNECT CHANNEL','success'),{callback_data:'connect:channel'})]);rows.push([Object.assign(uiButton('↩️ BACK','primary'),{callback_data:'back'})]);}else{if(selected.length)rows.push(...selected.slice(0,30).map(x=>[Object.assign(uiButton(`${x.kind==='group'?'👥':'📢'} ${x.title||x.chat_id}`,'primary'),{callback_data:`open:${x.kind}:${x.chat_id}`})]));else rows.push([Object.assign(uiButton('ℹ️ NO CONNECTED TARGETS','primary'),{callback_data:'noop'})]);rows.push([Object.assign(uiButton('↩️ BACK','primary'),{callback_data:'connections'})]);}return api.sendMessage(chatId,uiText(`⚙️ CONNECTED TARGETS\n\n👥 Groups: ${groups.length}\n📢 Channels: ${channels.length}`),rows)}

async function connectChannelCommand(api,content,store,options,forwarded,arg){
 if(!store)return notConfigured(api,content.chat.id);
 if(forwarded)return connectAndOpenChannel(api,content,store,options,forwarded);
 if(!arg)return api.sendMessage(content.chat.id,uiText('📢 CHANNEL CONNECTION\n\nSend a public @username or numeric channel ID.\nFor a private channel, send: channel ID | invite link.\nYou can also forward one of its posts after making me an admin.\n\nExample: @mychannel\nExample: -1001234567890 | https://t.me/+YourInviteLink'));
 let id=arg.trim();
 if(id.includes('|'))id=id.split('|')[0].trim();
 if(/^https?:\/\/t\.me\/\+|^https?:\/\/t\.me\/joinchat\//i.test(id))return api.sendMessage(content.chat.id,uiText('⚠️ A private invite link alone cannot identify the channel. Send the channel ID together with the invite link, or forward a channel post.'));
 if(/^https?:\/\/t\.me\//i.test(id)){const m=id.match(/t\.me\/(?:c\/)?([A-Za-z0-9_+-]+)/i);if(m&&!m[1].startsWith('-')&&!m[1].startsWith('+'))id='@'+m[1]}
 const check=await verifyChannelSetup(api,id);if(!check.ok){const numeric=Number(id);if(!numeric)return api.sendMessage(content.chat.id,uiText(`⚠️ ${check.error}`));const retry=await verifyChannelSetup(api,numeric);if(!retry.ok)return api.sendMessage(content.chat.id,uiText(`⚠️ ${retry.error}`));return saveChannelWithOptions(api,content,store,retry.chat,options)}
 return saveChannelWithOptions(api,content,store,check.chat,options);
}
async function saveChannelWithOptions(api,content,store,chat,options){if(!(await verifyAdmin(api,chat.id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ You must be a channel admin to connect this channel.'));await store.connect(content.from.id,chat.id,'channel',chat.title||'Channel');return showChannelSettings(api,content.chat.id,content.from.id,chat.id,store,options)}
async function openChannelFromForward(api,content,store,options,forwarded){if(!forwarded)return api.sendMessage(content.chat.id,uiText('📢 Forward a post from the channel here, then use /joinsetting.'));return connectAndOpenChannel(api,content,store,options,forwarded)}

function getRequiredChannels(s){if(Array.isArray(s.required_channels)&&s.required_channels.length)return s.required_channels;return s.required_channel_id?[{id:Number(s.required_channel_id),url:s.required_channel_url||'',title:'Required Channel'}]:[]}
function shortChannelName(c){return String(c.title||c.url||c.id).replace(/^@/,'').slice(0,28)}
function formatRequiredChannels(chs){return chs.length?chs.map((c,i)=>`${i+1}. ${escapeHtml(c.title||c.url||String(c.id))}`).join('\n'):'None'}

async function showGroupSettings(api,chatId,userId,targetId,store,options,editMessageId=null){const s=await store.getGroupSettings(targetId),required=getRequiredChannels(s);const text=uiText(`⚙️ GROUP SETTINGS\n\n👋 Welcome: ${s.welcome_enabled?'🟢 ON':'🔴 OFF'}\n❤️ Reactions: ${s.reactions_enabled?'🟢 ON':'🔴 OFF'}\n🔐 Required Channels: ${required.length}`);const kb=[[Object.assign(uiButton(s.welcome_enabled?'👋 WELCOME ON':'👋 WELCOME OFF',s.welcome_enabled?'success':'danger'),{callback_data:`gs:welcome:${targetId}:${s.welcome_enabled?0:1}`}),Object.assign(uiButton('📝 MESSAGE','primary'),{callback_data:`input:wmsg:${targetId}`})],[Object.assign(uiButton('👤 ONLY USER','primary'),{callback_data:`gs:wmode:${targetId}:only_user`}),Object.assign(uiButton('👥 GROUP','primary'),{callback_data:`gs:wmode:${targetId}:group`})],[Object.assign(uiButton('🔘 BUTTONS','primary'),{callback_data:`buttons:welcome:${targetId}`})],[Object.assign(uiButton(s.reactions_enabled?'❤️ REACTIONS ON':'❤️ REACTIONS OFF',s.reactions_enabled?'success':'danger'),{callback_data:`gs:react:${targetId}:${s.reactions_enabled?0:1}`}),Object.assign(uiButton('✏️ REACTIONS','primary'),{callback_data:`input:reactions:${targetId}`})],[Object.assign(uiButton(s.required_enabled?'🔐 REQUIRED CHANNELS 🟢':'🔐 REQUIRED CHANNELS 🔴','primary'),{callback_data:`reqset:${targetId}`})],[Object.assign(uiButton('👁 PREVIEW','success'),{callback_data:`preview:welcome:${targetId}`}),Object.assign(uiButton('🔌 DISCONNECT','danger'),{callback_data:`disconnect:group:${targetId}`})],[Object.assign(uiButton('↩️ CONNECTIONS','primary'),{callback_data:'connections'})]];return editMessageId?api.editMessageText(chatId,editMessageId,text,kb):api.sendMessage(chatId,text,kb)}
async function showChannelSettings(api,chatId,userId,targetId,store,options,editMessageId=null){const s=await store.getGroupSettings(targetId);const text=uiText(`📢 CHANNEL SETTINGS\n\n❤️ Reactions: ${s.reactions_enabled?'🟢 ON':'🔴 OFF'}\n🛡️ Join Requests: ${s.join_enabled?'🟢 ON':'🔴 OFF'}\nMode: ${s.join_mode==='auto_accept'?'✅ AUTO ACCEPT':'🔔 NOTIFY ONLY'}`);const kb=[[Object.assign(uiButton(s.reactions_enabled?'❤️ REACTIONS ON':'❤️ REACTIONS OFF',s.reactions_enabled?'success':'danger'),{callback_data:`cs:react:${targetId}:${s.reactions_enabled?0:1}`})],[Object.assign(uiButton('✏️ CUSTOM REACTIONS','primary'),{callback_data:`input:reactions:${targetId}:channel`})],[Object.assign(uiButton(s.join_enabled?'🛡️ REQUESTS ON':'🛡️ REQUESTS OFF',s.join_enabled?'success':'danger'),{callback_data:`cs:join:${targetId}:${s.join_enabled?0:1}`}),Object.assign(uiButton(s.join_mode==='auto_accept'?'🔔 NOTIFY ONLY':'✅ AUTO ACCEPT','primary'),{callback_data:`cs:mode:${targetId}:${s.join_mode==='auto_accept'?'notify':'auto_accept'}`})],[Object.assign(uiButton('📝 REQUEST MESSAGE','primary'),{callback_data:`input:jmsg:${targetId}`})],[Object.assign(uiButton('🔘 REQUEST BUTTONS','primary'),{callback_data:`buttons:join:${targetId}`})],[Object.assign(uiButton('👁 PREVIEW','success'),{callback_data:`preview:join:${targetId}`}),Object.assign(uiButton('🔌 DISCONNECT','danger'),{callback_data:`disconnect:channel:${targetId}`})],[Object.assign(uiButton('↩️ CONNECTIONS','primary'),{callback_data:'connections'})]];return editMessageId?api.editMessageText(chatId,editMessageId,text,kb):api.sendMessage(chatId,text,kb)}

async function beginInput(api,q,store,mode,targetId,prompt,payload={}){await store.setPending(q.from.id,targetId,mode,{...payload,panel_chat_id:q.message.chat.id,panel_message_id:q.message.message_id});await api.answerCallbackQuery(q.id);return api.editMessageText(q.message.chat.id,q.message.message_id,uiText(prompt),[[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'inputcancel'})]])}
function buttonKey(target){return target==='join'?'join_buttons':target==='required'?'required_buttons':'welcome_buttons'}
function buttonKind(target){return target==='join'?'channel':target==='required'?'group':'group'}
function flattenButtons(rows){return (rows||[]).flatMap((row,ri)=>row.map((b,ci)=>({b,ri,ci})))}
function rebuildRows(items,rowMode=2){const rows=[];for(let i=0;i<items.length;i+=rowMode)rows.push(items.slice(i,i+rowMode));return rows}

async function finishPending(api,content,pending,Reactions,store,botUsername,options){const value=(content.text||'').trim(),p=pending.payload||{};if(!value)return api.sendMessage(content.chat.id,uiText('⚠️ Input cannot be empty. Please try again.'));
 if(pending.mode==='reqchannel')return addRequiredChannel(api,content,pending.chatId,value,store,options,pending.payload);
 await store.clearPending(content.from.id);
 if(pending.mode==='wmsg'||pending.mode==='jmsg'){await store.updateGroupSettings(pending.chatId,{[pending.mode==='wmsg'?'welcome_message':'join_message']:value});return pendingPanel(api,pending,p,pending.chatId,pending.mode==='wmsg'?'group':'channel',store,options)}
 if(pending.mode==='reactions'){const r=splitEmojis(value).slice(0,20);if(!r.length)return api.sendMessage(content.chat.id,uiText('⚠️ No valid emoji reactions found. Send emoji only, for example: 👍 ❤️ 🔥'));await store.setReactions(pending.chatId,r);return pendingPanel(api,pending,p,pending.chatId,p.channel?'channel':buttonKind('welcome'),store,options)}
 if(pending.mode==='button_name'){const draft={target:p.target,name:value};await store.setPending(content.from.id,pending.chatId,'button_link',{...draft,panel_chat_id:p.panel_chat_id,panel_message_id:p.panel_message_id});return api.editMessageText(p.panel_chat_id,p.panel_message_id,uiText('🔗 NOW SEND THE BUTTON LINK.\n\nEXAMPLE: https://example.com'),[[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'inputcancel'})]])}
 if(pending.mode==='button_link'){if(!/^https?:\/\//i.test(value))return api.sendMessage(content.chat.id,uiText('⚠️ Please send a valid http:// or https:// link.'));await store.setPending(content.from.id,pending.chatId,'button_color',{...p,link:value,panel_chat_id:p.panel_chat_id,panel_message_id:p.panel_message_id});return api.editMessageText(p.panel_chat_id,p.panel_message_id,uiText('🎨 CHOOSE THE BUTTON COLOR.'),[[Object.assign(uiButton('🔵 PRIMARY','primary'),{callback_data:'inputcolor:primary'}),Object.assign(uiButton('🟢 SUCCESS','success'),{callback_data:'inputcolor:success'})],[Object.assign(uiButton('🔴 DANGER','danger'),{callback_data:'inputcolor:danger'})],[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'inputcancel'})]])}
 if(pending.mode==='button_edit_name'){const key=buttonKey(p.target),s=await store.getGroupSettings(pending.chatId),rows=s[key]||[];if(rows[p.ri]?.[p.ci])rows[p.ri][p.ci].text=value;await store.updateGroupSettings(pending.chatId,{[key]:rows});return buttonManager(api,content.chat.id,p.panel_message_id,pending.chatId,p.target,store)}
 if(pending.mode==='button_edit_link'){if(!/^https?:\/\//i.test(value))return api.sendMessage(content.chat.id,uiText('⚠️ Please send a valid http:// or https:// link.'));const key=buttonKey(p.target),s=await store.getGroupSettings(pending.chatId),rows=s[key]||[];if(rows[p.ri]?.[p.ci])rows[p.ri][p.ri===p.ri?p.ci:p.ci].url=value;await store.updateGroupSettings(pending.chatId,{[key]:rows});return buttonManager(api,content.chat.id,p.panel_message_id,pending.chatId,p.target,store)}
 if(pending.mode==='button_row'){const row=Math.max(1,Math.min(2,Number(value)||1)),key=buttonKey(p.target),s=await store.getGroupSettings(pending.chatId),flat=flattenButtons(s[key]||[]).map(x=>x.b);await store.updateGroupSettings(pending.chatId,{[key]:rebuildRows(flat,row)});return buttonManager(api,content.chat.id,p.panel_message_id,pending.chatId,p.target,store)}
 return pendingPanel(api,pending,p,pending.chatId,p.channel?'channel':'group',store,options)
}
async function addRequiredChannel(api,content,groupId,value,store,options,payload){
 let id=value.trim(),url='';
 if(value.includes('|')){const parts=value.split('|').map(x=>x.trim());id=parts[0];url=parts[1]||''}
 let chatId=/^-?\d+$/.test(id)?Number(id):id;
 if(/^https?:\/\/t\.me\//i.test(id)){const m=id.match(/t\.me\/([A-Za-z0-9_]+)/i);if(m)chatId='@'+m[1]}
 const fail=async(message)=>{
  const kb=[[Object.assign(uiButton('🔄 TRY AGAIN','success'),{callback_data:`reqretry:${groupId}`}),Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:`reqcancel:${groupId}`})]];
  if(payload?.panel_chat_id&&payload?.panel_message_id){try{return await api.editMessageText(payload.panel_chat_id,payload.panel_message_id,uiText(`⚠️ ${message}\n\nPlease try again.`),kb)}catch(_){} }
  return api.sendMessage(content.chat.id,uiText(`⚠️ ${message}\n\nPlease try again.`),kb);
 };
 if(!(await verifyBotAdmin(api,groupId)))return fail('Make me an admin in that group first.');
 const check=await verifyChannelSetup(api,chatId);
 if(!check.ok)return fail(check.error);
 const c=check.chat;
 if(!(await verifyAdmin(api,c.id,content.from.id)))return fail('You are not an admin of this channel.');
 if(!url&&!c.username)return fail('This is a private channel. Send the channel ID together with its invite/join-request link.');
 const s=await store.getGroupSettings(groupId),chs=getRequiredChannels(s);
 if(chs.some(x=>Number(x.id)===Number(c.id)))return fail('This channel is already in the required-channel list.');
 const finalUrl=url||(c.username?`https://t.me/${c.username}`:'');
 chs.push({id:Number(c.id),url:finalUrl,title:c.title||'Required Channel'});
 await store.updateGroupSettings(groupId,{required_channels:chs,required_channel_id:Number(c.id),required_channel_url:finalUrl,required_enabled:true});
 await store.clearPending(content.from.id);
 return showRequiredChannels(api,payload.panel_chat_id,payload.panel_message_id,groupId,store);
}

async function pendingPanel(api,pending,p,targetId,kind,store,options){const panelId=p.panel_message_id,chatId=p.panel_chat_id;if(!panelId)return kind==='group'?showGroupSettings(api,chatId||pending.chatId,pending.chatId,targetId,store,options):showChannelSettings(api,chatId||pending.chatId,pending.chatId,targetId,store,options);return kind==='group'?showGroupSettings(api,chatId,pending.chatId,targetId,store,options,panelId):showChannelSettings(api,chatId,pending.chatId,targetId,store,options,panelId)}

async function sendStart(api,content,botUsername,options,arg=''){if(arg.startsWith('group_')){const id=Number(arg.slice(6));if(id&&await verifyAdmin(api,id,content.from.id)&&options.store){const chat=await api.getChat(id).catch(()=>({}));await options.store.connect(content.from.id,id,'group',chat.title||`Group ${id}`);return showGroupSettings(api,content.chat.id,content.from.id,id,options.store,options)}}const name=escapeHtml(content.from?.first_name||'UserName'),text=startMessage.replace('UserName',name),updates=options.updatesUrl||`https://t.me/${botUsername}`,support=options.supportUrl||`https://t.me/${botUsername}`;const kb=[[Object.assign(uiButton('⇆ ADD ME TO YOUR CHANNELS ⇆','success'),{url:`https://t.me/${botUsername}?startchannel=botstart`})],[Object.assign(uiButton('⇆ ADD ME TO YOUR GROUPS ⇆','success'),{url:`https://t.me/${botUsername}?startgroup=botstart`})],[Object.assign(uiButton('❓ HELP','primary'),{callback_data:'help'}),Object.assign(uiButton('⚙️ SETTINGS','primary'),{callback_data:'settings'})],[Object.assign(uiButton('• UPDATES •','primary'),{url:updates}),Object.assign(uiButton('• SUPPORT •','primary'),{url:support})],[Object.assign(uiButton('💰 DONATION','success'),{callback_data:'donate'})]];if(options.startAnimation)try{return await api.sendAnimation(content.chat.id,options.startAnimation,text,kb)}catch(_){}return api.sendMessage(content.chat.id,text,kb)}
async function showHelp(api,content,botUsername,options){const text=uiText(`❖ HELP CENTER\n\n🤖 WHAT I DO\n• Auto Reaction: automatically reacts to eligible group and channel messages.\n• Group Settings: manage each connected group from one private dashboard.\n• Channel Settings: connect channels, customize reactions and manage join requests.\n\n⚙️ GROUP FEATURES\n• Welcome: turn it on/off, choose Group or Only User mode, edit message and buttons.\n• Required Channels: add multiple channels; new members must join all before chatting.\n• Reactions: turn auto reactions on/off and choose custom emojis.\n\n📢 CHANNEL FEATURES\n• /connectchannel: connect a public channel or a verified private channel.\n• /mychannels: open your connected channels.\n• Reactions: customize the emojis used by the bot.\n• Join Requests: Notify Only or Auto Accept, with custom message and buttons.\n\n👤 USER COMMANDS\n/start — open the main menu.\n/help — show this help.\n/reactions — open reaction settings for a connected chat/channel.\n/donate — support the bot.\n\n👥 GROUP ADMIN COMMANDS\n/groupsetting — connect and manage the group.\n/welcome — open group settings quickly.\n/reactions_on — enable reactions.\n/reactions_off — disable reactions.\n\n📢 CHANNEL ADMIN COMMANDS\n/connectchannel — connect a channel.\n/mychannels — list connected channels.\n/joinsetting — open channel join-request settings.\n\n📣 BROADCAST\nBot admins can broadcast a replied message to Users, Groups, Channels, or All. Users includes channel-request users.`);const kb=[[Object.assign(uiButton('💬 SUPPORT','primary'),{url:options.supportUrl||`https://t.me/${botUsername}`}),Object.assign(uiButton('💰 DONATION','success'),{callback_data:'donate'})],[Object.assign(uiButton('◀️ BACK','primary'),{callback_data:'back'})]];return api.sendMessage(content.chat.id,text,kb)}
async function showWelcomeEdited(api,q,botUsername,options){const name=escapeHtml(q.from?.first_name||'there'),text=startMessage.replace('UserName',name),kb=[[Object.assign(uiButton('⇆ ADD ME TO YOUR CHANNELS ⇆','success'),{url:`https://t.me/${botUsername}?startchannel=botstart`})],[Object.assign(uiButton('⇆ ADD ME TO YOUR GROUPS ⇆','success'),{url:`https://t.me/${botUsername}?startgroup=botstart`})],[Object.assign(uiButton('❓ HELP','primary'),{callback_data:'help'}),Object.assign(uiButton('⚙️ SETTINGS','primary'),{callback_data:'settings'})],[Object.assign(uiButton('• UPDATES •','primary'),{url:options.updatesUrl||`https://t.me/${botUsername}`}),Object.assign(uiButton('• SUPPORT •','primary'),{url:options.supportUrl||`https://t.me/${botUsername}`})],[Object.assign(uiButton('💰 DONATION','success'),{callback_data:'donate'})]];return api.editMessageText(q.message.chat.id,q.message.message_id,text,kb)}
async function sendDonate(api,id,options){if(options.donateAnimation)try{await api.sendAnimation(id,options.donateAnimation,uiText('🙏 Support Auto Reaction Bot ✨'))}catch(_){}return api.sendInvoice(id,uiText('Donate to Auto Reactions Bot ✨'),uiText(donateMessage),'{}','', 'donate','XTR',[{label:'Pay ⭐️5',amount:5}])}
async function sendStats(api,id,store){const c=await store.counts(),r=store.channelRequestCount?await store.channelRequestCount():0;return api.sendMessage(id,uiText(`📊 BOT STATS\n\n👤 Users: ${c.users}\n👥 Groups: ${c.groups}\n📢 Channels: ${c.channels}\n📨 Channel Request Users: ${r}\n\n🧮 Total Chats: ${c.users+c.groups+c.channels}`))}

async function askBroadcast(api,content,options){const {store,enqueueBroadcast}=options;if(!store||!enqueueBroadcast)return notConfigured(api,content.chat.id);const reply=content.reply_to_message;if(!reply){const text=uiText('📢 BROADCAST HELP\n\n<blockquote><b>⚠️ PLEASE REPLY TO ANY MESSAGE TO START A BROADCAST.</b></blockquote>\n\n📌 AUDIENCE OPTIONS:\n\n👤 USERS\n→ NORMAL USERS + CHANNEL REQUEST USERS\n\n👥 GROUPS\n→ ALL CONNECTED GROUPS\n\n📢 CHANNELS\n→ ALL CONNECTED CHANNELS\n\n🌐 ALL\n→ USERS + GROUPS + CHANNELS\n\n💡 HOW TO USE:\n1. Reply to the message you want to send.\n2. Send /broadcast.\n3. Select the audience.\n4. Choose Copy or Forward.\n5. Choose Pin or Without Pin.\n6. Confirm and send.');return api.sendMessage(content.chat.id,text,[[Object.assign(uiButton('❌ CLOSE','danger'),{callback_data:'bcx'})]])}const usersCount=store.audienceCount?await store.audienceCount('users'):0,groupsCount=store.audienceCount?await store.audienceCount('groups'):0,channelsCount=store.audienceCount?await store.audienceCount('channels'):0,allCount=store.audienceCount?await store.audienceCount('all'):usersCount+groupsCount+channelsCount,base=`${content.chat.id}:${reply.message_id}`;const bcButtons=[[Object.assign(uiButton(`👤 USERS • ${usersCount}`,'primary'),{callback_data:`bc:${base}:users`}),Object.assign(uiButton(`👥 GROUPS • ${groupsCount}`,'primary'),{callback_data:`bc:${base}:groups`})],[Object.assign(uiButton(`📢 CHANNELS • ${channelsCount}`,'primary'),{callback_data:`bc:${base}:channels`}),Object.assign(uiButton(`🌐 ALL • ${allCount}`,'success'),{callback_data:`bc:${base}:all`})],[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]];return api.sendMessage(content.chat.id,uiText(`📢 BROADCAST\n\n👤 Users: ${usersCount}\n👥 Connected Groups: ${groupsCount}\n📢 Connected Channels: ${channelsCount}\n\nSelect who should receive this message.`),bcButtons)}

async function showReactionSettings(api,content,defaults,store,options,forwarded){if(!store)return notConfigured(api,content.chat.id);let id=content.chat.id,title=content.chat.title||'this chat';if(content.chat.type==='private'){if(!forwarded)return api.sendMessage(content.chat.id,uiText('⚙️ Forward a channel post here and use /reactions, or open a connected channel from Settings.'));id=forwarded.id;title=forwarded.title||'Channel';if(!(await verifyAdmin(api,id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ Channel admins only.'))}else if(!['group','supergroup','channel'].includes(content.chat.type)||!(await verifyAdmin(api,id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ Admins only.'));const on=await store.isReactionsEnabled(id),r=await store.getReactions(id);return api.sendMessage(content.chat.id,uiText(`⚙️ REACTION SETTINGS — ${title}\n\nStatus: ${on?'🟢 ON':'🔴 OFF'}\nReactions: ${(r||defaults).join(' ')}\n\n💡 Custom reactions replace the default reaction list for this chat.`),[[Object.assign(uiButton(on?'🔴 TURN OFF':'🟢 TURN ON',on?'danger':'success'),{callback_data:`rs:${on?'off':'on'}:${id}`}),Object.assign(uiButton('✏️ CUSTOM','primary'),{callback_data:`input:reactions:${id}`})],[Object.assign(uiButton('🔄 RESET','primary'),{callback_data:`rs:reset:${id}`})]])}
async function setGroupReactionState(api,c,en,store){if(!(await verifyGroupAdmin(api,c)))return api.sendEphemeralMessage(c.chat.id,c.from.id,uiText('⚠️ Only group admins can change reaction settings.'));await store.setReactionsEnabled(c.chat.id,en);return api.sendEphemeralMessage(c.chat.id,c.from.id,uiText(en?'🟢 Auto reactions enabled.':'🔴 Auto reactions disabled.'))}
async function setForwardedChannelState(api,c,ch,en,store){if(!(await verifyAdmin(api,ch.id,c.from.id)))return api.sendMessage(c.chat.id,uiText('⚠️ Channel admins only.'));await store.setReactionsEnabled(ch.id,en);return api.sendMessage(c.chat.id,uiText(`${en?'🟢':'🔴'} Reactions ${en?'enabled':'disabled'} for ${ch.title||'the channel'}.`))}

async function showRequiredChannels(api,chatId,msgId,id,store){const s=await store.getGroupSettings(id),chs=getRequiredChannels(s);const rows=chs.map((c,i)=>[Object.assign(uiButton(`${i+1}. ${shortChannelName(c)}`,'primary'),{callback_data:`reqview:${id}:${i}`})]);rows.push([Object.assign(uiButton('➕ ADD CHANNEL','success'),{callback_data:`reqadd:${id}`}),Object.assign(uiButton('🔘 BUTTONS','primary'),{callback_data:`buttons:required:${id}`})]);rows.push([Object.assign(uiButton(s.required_enabled?'🟢 TURN OFF':'🔴 TURN ON',s.required_enabled?'danger':'success'),{callback_data:`reqtoggle:${id}:${s.required_enabled?0:1}`})]);rows.push([Object.assign(uiButton('🗑 REMOVE CHANNEL','danger'),{callback_data:`reqremoveone:${id}`}),Object.assign(uiButton('🗑 REMOVE ALL','danger'),{callback_data:`reqremoveall:${id}`})]);rows.push([Object.assign(uiButton('↩️ BACK TO GROUP SETTINGS','primary'),{callback_data:`open:group:${id}`})]);const text=uiText(`🔐 REQUIRED CHANNELS\n\nStatus: ${s.required_enabled&&chs.length?'🟢 ON':'🔴 OFF'}\n\n${formatRequiredChannels(chs)}\n\n💡 When ON, users must be members of every required channel before chatting.`);return api.editMessageText(chatId,msgId,text,rows)}
async function buttonManager(api,chatId,msgId,id,target,store){const s=await store.getGroupSettings(id),key=buttonKey(target),b=s[key]||[];const rows=[[Object.assign(uiButton('➕ ADD BUTTON','success'),{callback_data:`buttonadd:${target}:${id}`})]];for(const [ri,row] of b.entries())for(const [ci,x] of row.entries())rows.push([Object.assign(uiButton(`🔘 ${x.text}`,'primary'),{callback_data:`bedit:${target}:${id}:${ri}:${ci}`})]);rows.push([Object.assign(uiButton('↕️ LAYOUT 1/ROW','primary'),{callback_data:`blayout:${target}:${id}:1`}),Object.assign(uiButton('↔️ LAYOUT 2/ROW','primary'),{callback_data:`blayout:${target}:${id}:2`})]);rows.push([Object.assign(uiButton('👁 PREVIEW','success'),{callback_data:`preview:${target==='join'?'join':target==='required'?'required':'welcome'}:${id}`})]);rows.push([Object.assign(uiButton('↩️ BACK','primary'),{callback_data:target==='required'?`reqset:${id}`:target==='join'?`open:channel:${id}`:`open:group:${id}`})]);return api.editMessageText(chatId,msgId,uiText(`🔘 ${target==='join'?'REQUEST':target.toUpperCase()} BUTTONS\n\nTap a button to edit it. Add as many as you need. The bot will stay here until you press Back.`),rows)}

async function onCallback(q,api,options){const {store=null,adminIds=[],enqueueBroadcast=null}=options,d=q.data||'',chatId=q.message?.chat?.id,msgId=q.message?.message_id;
 if(d==='donate'){await api.answerCallbackQuery(q.id);return sendDonate(api,chatId,options)}
 if(d==='help'){await api.answerCallbackQuery(q.id);try{await api.deleteMessage(chatId,msgId)}catch(_){}return showHelp(api,{chat:{id:chatId},from:q.from},options.botUsername,options)}
 if(d==='back'){await api.answerCallbackQuery(q.id);return showWelcomeEdited(api,q,options.botUsername,options)}
 if(d==='settings'||d==='connections'){await api.answerCallbackQuery(q.id);return showConnections(api,chatId,q.from.id,store,options)}
 if(d.startsWith('reqretry:')){const id=Number(d.split(':')[1]);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(!(await verifyBotAdmin(api,id)))return api.answerCallbackQuery(q.id,'Make me an admin in this group first.',true);await store.setPending(q.from.id,id,'reqchannel',{panel_chat_id:chatId,panel_message_id:msgId,context:'required'});await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText('➕ ADD REQUIRED CHANNEL\n\nSend @channelusername or numeric channel ID.\nFor a public link, send https://t.me/channelname.\nFor a private channel, send: channel ID | invite link.'),[[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:`reqcancel:${id}`})]])}
 if(d.startsWith('reqcancel:')){const id=Number(d.split(':')[1]);await store.clearPending(q.from.id);await api.answerCallbackQuery(q.id);return showRequiredChannels(api,chatId,msgId,id,store)}
 if(d==='inputcancel'){const p=await store.getPending(q.from.id);await store.clearPending(q.from.id);await api.answerCallbackQuery(q.id);if(p?.payload?.target)return buttonManager(api,chatId,msgId,p.chatId,p.payload.target,store);if(p?.payload?.context==='required')return showRequiredChannels(api,chatId,msgId,p.chatId,store);if(p?.payload?.channel)return showChannelSettings(api,chatId,q.from.id,p.chatId,store,options,msgId);if(['wmsg','jmsg','reactions'].includes(p?.mode))return p.mode==='jmsg'?showChannelSettings(api,chatId,q.from.id,p.chatId,store,options,msgId):showGroupSettings(api,chatId,q.from.id,p.chatId,store,options,msgId);return showConnections(api,chatId,q.from.id,store,options)}
 if(d==='bcinfo'){return api.answerCallbackQuery(q.id,'Reply to a message, then send /broadcast.',true)}
 if(d==='connect:channel'){await api.answerCallbackQuery(q.id);return api.sendMessage(chatId,uiText('📢 Use /connectchannel and send a public @username or channel ID. For a private channel, forward one of its posts after making me an admin.'))}
 if(d==='connect:group'){await api.answerCallbackQuery(q.id);return api.sendMessage(chatId,uiText(`👥 Add me to your group as an admin, then send /groupsetting there.\n\nhttps://t.me/${options.botUsername}?startgroup=botstart`))}
 if(d.startsWith('pick:')){const kind=d.split(':')[1],list=await store.connections(q.from.id,kind);await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText(`⚙️ SELECT ${kind.toUpperCase()}`),list.slice(0,30).map(x=>[Object.assign(uiButton(x.title||`${kind} ${x.chat_id}`,'primary'),{callback_data:`open:${kind}:${x.chat_id}`})]).concat([[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:'connections'})]]))}
 if(d.startsWith('open:')){const [,kind,id]=d.split(':');if(!(await verifyAdmin(api,Number(id),q.from.id)))return api.answerCallbackQuery(q.id,'You are no longer an admin.',true);await api.answerCallbackQuery(q.id);return kind==='group'?showGroupSettings(api,chatId,q.from.id,Number(id),store,options,msgId):showChannelSettings(api,chatId,q.from.id,Number(id),store,options,msgId)}
 if(d.startsWith('disconnect:')){const [,kind,id]=d.split(':');await store.disconnect(q.from.id,Number(id));await api.answerCallbackQuery(q.id,'Disconnected');return showConnections(api,chatId,q.from.id,store,options)}
 if(d.startsWith('gs:')){const [,a,idRaw,v]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(a==='welcome')await store.updateGroupSettings(id,{welcome_enabled:v==='1'});else if(a==='wmode')await store.updateGroupSettings(id,{welcome_mode:v==='only_user'?'only_user':'group'});else if(a==='react')await store.setReactionsEnabled(id,v==='1');await api.answerCallbackQuery(q.id);return showGroupSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('cs:')){const [,a,idRaw,v]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(a==='react')await store.setReactionsEnabled(id,v==='1');else if(a==='join')await store.updateGroupSettings(id,{join_enabled:v==='1'});else if(a==='mode')await store.updateGroupSettings(id,{join_mode:v==='auto_accept'?'auto_accept':'notify'});await api.answerCallbackQuery(q.id);return showChannelSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('rs:')){const [,a,idRaw]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(a==='reset')await store.resetReactions(id);else await store.setReactionsEnabled(id,a==='on');await api.answerCallbackQuery(q.id);return showChannelSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('input:')){const [,mode,idRaw,kind]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);const prompt={wmsg:'📝 Send your welcome message.\n\nVariables: {name} {username} {mention} {group}',jmsg:'📝 Send your join-request message.\n\nVariables: {name} {username} {mention} {group}',reactions:'✏️ Send 1–20 emoji reactions.\n\nExample: 👍 ❤️ 🔥'}[mode]||'📝 Send the new value.';return beginInput(api,q,store,mode,id,prompt,{channel:kind==='channel'})}
 if(d.startsWith('reqset:')){const id=Number(d.split(':')[1]);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);await api.answerCallbackQuery(q.id);return showRequiredChannels(api,chatId,msgId,id,store)}
 if(d.startsWith('reqtoggle:')){const [,idRaw,v]=d.split(':'),id=Number(idRaw),on=v==='1';if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);const s=await store.getGroupSettings(id),chs=getRequiredChannels(s);if(on&&!chs.length)return api.answerCallbackQuery(q.id,'Add at least one required channel first.',true);if(on&&!(await verifyBotAdmin(api,id)))return api.answerCallbackQuery(q.id,'Make me an admin in this group first.',true);await store.updateGroupSettings(id,{required_enabled:on});await api.answerCallbackQuery(q.id,on?'Required channel enforcement ON':'Required channel enforcement OFF');return showRequiredChannels(api,chatId,msgId,id,store)}
 if(d.startsWith('reqadd:')){const id=Number(d.split(':')[1]);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(!(await verifyBotAdmin(api,id)))return api.answerCallbackQuery(q.id,'Make me an admin in this group first.',true);return beginInput(api,q,store,'reqchannel',id,'➕ ADD REQUIRED CHANNEL\n\nSend @channelusername or numeric channel ID.\nFor a public link, send https://t.me/channelname.\nFor a private channel, forward a channel post to me first.\n\nOptional: ID | invite/public link',{panel_chat_id:chatId,panel_message_id:msgId,context:'required'})}
 if(d.startsWith('reqremoveone:')){const id=Number(d.split(':')[1]),s=await store.getGroupSettings(id),chs=getRequiredChannels(s);if(!chs.length)return api.answerCallbackQuery(q.id,'No required channels configured.',true);return api.editMessageText(chatId,msgId,uiText('🗑️ SELECT A REQUIRED CHANNEL TO REMOVE.'),chs.map((c,i)=>[Object.assign(uiButton(`🗑 ${i+1}. ${shortChannelName(c)}`,'danger'),{callback_data:`reqdel:${id}:${i}`})]).concat([[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`reqset:${id}`})]]))}
 if(d.startsWith('reqdel:')){const [,idRaw,idxRaw]=d.split(':'),id=Number(idRaw),idx=Number(idxRaw),s=await store.getGroupSettings(id),chs=getRequiredChannels(s);chs.splice(idx,1);await store.updateGroupSettings(id,{required_channels:chs,required_channel_id:chs[0]?.id||null,required_channel_url:chs[0]?.url||'',required_enabled:chs.length?s.required_enabled:false});await api.answerCallbackQuery(q.id,'Channel removed');return showRequiredChannels(api,chatId,msgId,id,store)}
 if(d.startsWith('reqremoveall:')){const id=Number(d.split(':')[1]);await store.updateGroupSettings(id,{required_channels:[],required_channel_id:null,required_channel_url:'',required_enabled:false});await api.answerCallbackQuery(q.id,'All required channels removed');return showRequiredChannels(api,chatId,msgId,id,store)}
 if(d.startsWith('reqcheck:')){const gid=Number(d.split(':')[1]),uid=q.from.id,s=await store.getGroupSettings(gid),chs=getRequiredChannels(s),missing=[];for(const c of chs){try{const m=await api.getChatMember(c.id,uid);if(!(['member','administrator','creator'].includes(m?.status)||(m?.status==='restricted'&&m?.is_member)))missing.push(c)}catch{missing.push(c)}}if(missing.length)return api.answerCallbackQuery(q.id,`Join all required channels first (${missing.length} left).`,true);try{await api.restrictChatMember(gid,uid,UNMUTE_PERMISSIONS)}catch{return api.answerCallbackQuery(q.id,'I cannot unmute you. Check my group permissions.',true)}await api.answerCallbackQuery(q.id,'Verified! You can chat now.');try{await api.deleteMessage(chatId,msgId)}catch(_){}return api.sendMessage(gid,uiText(`✅ ${q.from.first_name||'User'} has joined all required channels and can now chat.`))}
 if(d.startsWith('reqview:')){const [,idRaw,idxRaw]=d.split(':'),id=Number(idRaw),idx=Number(idxRaw),s=await store.getGroupSettings(id),c=getRequiredChannels(s)[idx];if(!c)return api.answerCallbackQuery(q.id,'Channel not found.',true);return api.editMessageText(chatId,msgId,uiText(`📢 REQUIRED CHANNEL ${idx+1}\n\nName: ${c.title||'Channel'}\nID: ${c.id}\nLink: ${c.url||'Not set'}\n\nThe bot must remain an admin in this channel.`),[[Object.assign(uiButton('🗑 REMOVE','danger'),{callback_data:`reqdel:${id}:${idx}`})],[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`reqset:${id}`})]])}
 if(d.startsWith('preview:')){const [,type,idRaw]=d.split(':'),id=Number(idRaw),s=await store.getGroupSettings(id);await api.answerCallbackQuery(q.id);if(type==='required')return api.sendMessage(chatId,uiText('🔐 REQUIRED CHANNEL PREVIEW\n\nPlease join all required channels before chatting.'),normalizeButtons(s.required_buttons));return api.sendMessage(chatId,type==='welcome'?renderTemplate(s.welcome_message||DEFAULT_WELCOME,q.from,{title:'Preview Group'}):renderTemplate(s.join_message||DEFAULT_JOIN,q.from,{title:'Preview Channel'}),normalizeButtons(type==='welcome'?s.welcome_buttons:s.join_buttons))}
 if(d.startsWith('buttons:')){const [,target,idRaw]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);await api.answerCallbackQuery(q.id);return buttonManager(api,chatId,msgId,id,target,store)}
 if(d.startsWith('buttonadd:')){const [,target,idRaw]=d.split(':'),id=Number(idRaw);return beginInput(api,q,store,'button_name',id,'➕ ADD BUTTON\n\nSend the button name.\n\nExample: Support',{target})}
 if(d.startsWith('bedit:')){const [,target,idRaw,ri,ci]=d.split(':'),id=Number(idRaw);return api.editMessageText(chatId,msgId,uiText('🔘 BUTTON SETTINGS\n\nChoose what you want to change.'),[[Object.assign(uiButton('✏️ RENAME','primary'),{callback_data:`brename:${target}:${id}:${ri}:${ci}`}),Object.assign(uiButton('🔗 CHANGE LINK','primary'),{callback_data:`blink:${target}:${id}:${ri}:${ci}`})],[Object.assign(uiButton('🎨 CHANGE COLOR','primary'),{callback_data:`bcolor:${target}:${id}:${ri}:${ci}`}),Object.assign(uiButton('🗑 DELETE','danger'),{callback_data:`bdel:${target}:${id}:${ri}:${ci}`})],[Object.assign(uiButton('⬆️ MOVE UP','primary'),{callback_data:`bmove:${target}:${id}:${ri}:${ci}:up`}),Object.assign(uiButton('⬇️ MOVE DOWN','primary'),{callback_data:`bmove:${target}:${id}:${ri}:${ci}:down`})],[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`buttons:${target}:${id}`})]])}
 if(d.startsWith('brename:')||d.startsWith('blink:')){const [kind,target,idRaw,ri,ci]=d.split(':'),id=Number(idRaw);return beginInput(api,q,store,kind==='brename'?'button_edit_name':'button_edit_link',id,kind==='brename'?'✏️ Send the new button name.':'🔗 Send the new button link.\n\nExample: https://example.com',{target,ri:Number(ri),ci:Number(ci),panel_chat_id:chatId,panel_message_id:msgId})}
 if(d.startsWith('bcolor:')){const [,target,idRaw,ri,ci]=d.split(':'),id=Number(idRaw);return api.editMessageText(chatId,msgId,uiText('🎨 CHOOSE BUTTON COLOR'),[[Object.assign(uiButton('🔵 PRIMARY','primary'),{callback_data:`bcolor_set:${target}:${id}:${ri}:${ci}:primary`})],[Object.assign(uiButton('🟢 SUCCESS','success'),{callback_data:`bcolor_set:${target}:${id}:${ri}:${ci}:success`})],[Object.assign(uiButton('🔴 DANGER','danger'),{callback_data:`bcolor_set:${target}:${id}:${ri}:${ci}:danger`})],[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`bedit:${target}:${id}:${ri}:${ci}`})]])}
 if(d.startsWith('bcolor_set:')){const [,target,idRaw,ri,ci,color]=d.split(':'),id=Number(idRaw),key=buttonKey(target),s=await store.getGroupSettings(id),rows=s[key]||[];if(rows[Number(ri)]?.[Number(ci)])rows[Number(ri)][Number(ci)].style=color;await store.updateGroupSettings(id,{[key]:rows});await api.answerCallbackQuery(q.id,'Color updated');return buttonManager(api,chatId,msgId,id,target,store)}
 if(d.startsWith('bmove:')){const [,target,idRaw,ri,ci,dir]=d.split(':'),id=Number(idRaw),key=buttonKey(target),s=await store.getGroupSettings(id),flat=flattenButtons(s[key]||[]).map(x=>x.b),idx=flat.findIndex((_,i)=>{const x=flattenButtons(s[key]||[])[i];return x.ri===Number(ri)&&x.ci===Number(ci)}),to=dir==='up'?idx-1:idx+1;if(idx<0||to<0||to>=flat.length)return api.answerCallbackQuery(q.id,'Already at the edge.',true);[flat[idx],flat[to]]=[flat[to],flat[idx]];await store.updateGroupSettings(id,{[key]:rebuildRows(flat,2)});await api.answerCallbackQuery(q.id,'Position updated');return buttonManager(api,chatId,msgId,id,target,store)}
 if(d.startsWith('bdel:')){const [,target,idRaw,ri,ci]=d.split(':'),id=Number(idRaw),key=buttonKey(target),s=await store.getGroupSettings(id),rows=s[key]||[];if(rows[Number(ri)])rows[Number(ri)].splice(Number(ci),1);await store.updateGroupSettings(id,{[key]:rows.filter(r=>r.length)});await api.answerCallbackQuery(q.id,'Button deleted');return buttonManager(api,chatId,msgId,id,target,store)}
 if(d.startsWith('blayout:')){const [,target,idRaw,n]=d.split(':'),id=Number(idRaw),key=buttonKey(target),s=await store.getGroupSettings(id),flat=flattenButtons(s[key]||[]).map(x=>x.b);await store.updateGroupSettings(id,{[key]:rebuildRows(flat,Number(n)===1?1:2)});await api.answerCallbackQuery(q.id,'Layout updated');return buttonManager(api,chatId,msgId,id,target,store)}
 if(d.startsWith('inputcolor:')){const color=d.split(':')[1],p=await store.getPending(q.from.id);if(!p||p.mode!=='button_color')return api.answerCallbackQuery(q.id,'Input session expired.',true);const s=await store.getGroupSettings(p.chatId),key=buttonKey(p.payload.target),rows=s[key]||[],flat=flattenButtons(rows).map(x=>x.b);if(flat.length>=16)return api.answerCallbackQuery(q.id,'Maximum 16 buttons reached.',true);flat.push({text:p.payload.name,url:p.payload.link,style:color});await store.updateGroupSettings(p.chatId,{[key]:rebuildRows(flat,2)});await store.clearPending(q.from.id);await api.answerCallbackQuery(q.id,'Button added');return buttonManager(api,chatId,msgId,p.chatId,p.payload.target,store)}
 if(d.startsWith('bc:'))return broadcastCallback(q,api,options);
 if(d==='bcx'){await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText('❌ BROADCAST CANCELLED.'))}
 await api.answerCallbackQuery(q.id);
}

async function broadcastCallback(q,api,options){
  const {store,enqueueBroadcast}=options;
  if(!options.adminIds.includes(q.from.id))return api.answerCallbackQuery(q.id,'Not allowed',true);
  const parts=String(q.data||'').split(':');
  if(parts[0]!=='bc'||parts.length<4)return api.answerCallbackQuery(q.id,'Invalid broadcast action',true);
  const fromChatId=Number(parts[1]);
  const sourceMessageId=Number(parts[2]);
  const audience=parts[3];
  if(!Number.isFinite(fromChatId)||!Number.isFinite(sourceMessageId)||!['users','groups','channels','all'].includes(audience))return api.answerCallbackQuery(q.id,'Invalid broadcast data',true);
  const mode=parts[4];
  const pin=parts[5];
  const action=parts[6];
  if(parts.length===4){
    await api.answerCallbackQuery(q.id);
    return api.editMessageText(q.message.chat.id,q.message.message_id,uiText('📢 SELECT AUDIENCE'),[
      [Object.assign(uiButton('👤 USERS','primary'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:users`}),Object.assign(uiButton('👥 GROUPS','primary'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:groups`})],
      [Object.assign(uiButton('📢 CHANNELS','primary'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:channels`}),Object.assign(uiButton('🌐 ALL','success'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:all`})],
      [Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]
    ]);
  }
  if(!mode){
    await api.answerCallbackQuery(q.id);
    return api.editMessageText(q.message.chat.id,q.message.message_id,uiText(`📢 ${audience.toUpperCase()} SELECTED\n\nChoose delivery mode.`),[
      [Object.assign(uiButton('📤 COPY','primary'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:${audience}:copy`}),Object.assign(uiButton('↪️ FORWARD','primary'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:${audience}:forward`})],
      [Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]
    ]);
  }
  if(pin===undefined){
    await api.answerCallbackQuery(q.id);
    return api.editMessageText(q.message.chat.id,q.message.message_id,uiText(`📢 ${audience.toUpperCase()} • ${mode.toUpperCase()}\n\nChoose pin option.`),[
      [Object.assign(uiButton('📌 PIN','success'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:${audience}:${mode}:1`}),Object.assign(uiButton('🚫 WITHOUT PIN','primary'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:${audience}:${mode}:0`})],
      [Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]
    ]);
  }
  if(action!=='send'){
    await api.answerCallbackQuery(q.id);
    return api.editMessageText(q.message.chat.id,q.message.message_id,uiText(`📢 BROADCAST READY\n\n👤 Audience: ${audience.toUpperCase()}\n📤 Mode: ${mode.toUpperCase()}\n📌 Pin: ${pin==='1'?'YES':'NO'}\n\nSend this broadcast now?`),[
      [Object.assign(uiButton('🚀 SEND BROADCAST','success'),{callback_data:`bc:${fromChatId}:${sourceMessageId}:${audience}:${mode}:${pin}:send`})],
      [Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]
    ]);
  }
  const total=store.audienceCount?await store.audienceCount(audience):0;
  const job={audience,kinds:TARGETS[audience],fromChatId,messageId:sourceMessageId,statusChatId:q.message.chat.id,statusMessageId:q.message.message_id,afterId:Number.MIN_SAFE_INTEGER,total,sent:0,failed:0,removed:0,startedAt:Date.now(),mode,pin:pin==='1'};
  await api.answerCallbackQuery(q.id,'Broadcast queued');
  await editStatus(api,job,progressText(job));
  try{await enqueueBroadcast(job)}catch(e){await editStatus(api,job,errorText(job,e))}
}
